name = "dev-seemsgood"
main = "build/worker/shim.mjs"
compatibility_date = "2024-08-02"

[build]
command = "cargo install -q worker-build && worker-build --release"

[observability.logs]
enabled = true
invocation_logs = true

